/**
 * Poseidon Design System v2 — AI-readable component catalog.
 *
 * Every primitive is listed with its Zod schema name, variant list,
 * engine-color support flag, and a one-liner usage example.
 * AI agents and code-gen tools can use this catalog to discover
 * available components without reading each file individually.
 */

export const componentCatalog = {
  Surface: {
    description: 'Card/container with glass-morphism, elevation, and effect preset support',
    category: 'primitive' as const,
    schema: 'SurfacePropsSchema',
    variants: ['glass', 'elevated', 'inset', 'transparent'],
    engines: true,
    usage: '<Surface variant="glass" engine="protect" padding="md">...</Surface>',
  },
  Button: {
    description: 'Action button with engine-colored gradients and loading state',
    category: 'primitive' as const,
    schema: 'ButtonPropsSchema',
    variants: ['primary', 'secondary', 'ghost', 'danger', 'outline'],
    engines: true,
    usage: '<Button variant="primary" engine="protect">Approve</Button>',
  },
  Badge: {
    description: 'Status indicator with engine colors and optional glow',
    category: 'primitive' as const,
    schema: 'BadgePropsSchema',
    variants: ['default', 'success', 'warning', 'danger', 'info', 'engine'],
    engines: true,
    usage: '<Badge variant="success">Active</Badge>',
  },
  Input: {
    description: 'Text input with label, validation states, and icon support',
    category: 'primitive' as const,
    schema: 'InputPropsSchema',
    variants: [],
    engines: false,
    usage: '<Input label="Email" error="Invalid email" />',
  },
  Toggle: {
    description: 'Switch toggle with engine color support',
    category: 'primitive' as const,
    schema: 'TogglePropsSchema',
    variants: [],
    engines: true,
    usage: '<Toggle checked={true} engine="protect" label="Enable alerts" />',
  },
  Progress: {
    description: 'Linear or circular progress indicator with engine colors',
    category: 'primitive' as const,
    schema: 'ProgressPropsSchema',
    variants: ['linear', 'circular'],
    engines: true,
    usage: '<Progress value={75} engine="grow" showLabel />',
  },
  Avatar: {
    description: 'User avatar with image or initials fallback',
    category: 'primitive' as const,
    schema: 'AvatarPropsSchema',
    variants: [],
    engines: true,
    usage: '<Avatar src="/photo.jpg" fallback="JD" size="md" />',
  },
  Skeleton: {
    description: 'Loading placeholder with pulse animation',
    category: 'primitive' as const,
    schema: 'SkeletonPropsSchema',
    variants: ['line', 'circle', 'rect'],
    engines: false,
    usage: '<Skeleton variant="line" /><Skeleton variant="circle" width="40px" height="40px" />',
  },
  Separator: {
    description: 'Visual divider line',
    category: 'primitive' as const,
    schema: 'SeparatorPropsSchema',
    variants: [],
    engines: false,
    usage: '<Separator orientation="horizontal" />',
  },
  ScrollArea: {
    description: 'Custom scrollbar container',
    category: 'primitive' as const,
    schema: 'ScrollAreaPropsSchema',
    variants: [],
    engines: false,
    usage: '<ScrollArea maxHeight="400px">...</ScrollArea>',
  },

  // ── Composition ─────────────────────────────────────────────
  IconContainer: {
    description: 'Engine-themed icon wrapper with optional glow',
    category: 'composition' as const,
    schema: 'IconContainerPropsSchema',
    variants: ['default', 'glow'],
    engines: true,
    usage: '<IconContainer engine="protect" glow><ShieldIcon /></IconContainer>',
  },
  SectionHeader: {
    description: 'Section title with subtitle and optional action slot',
    category: 'composition' as const,
    schema: 'SectionHeaderPropsSchema',
    variants: [],
    engines: true,
    usage: '<SectionHeader title="Overview" engine="protect" action={<Button>View all</Button>} />',
  },
  DetailRow: {
    description: 'Key-value display row with optional icon',
    category: 'composition' as const,
    schema: 'DetailRowPropsSchema',
    variants: [],
    engines: true,
    usage: '<DetailRow label="Status" value="Active" engine="protect" />',
  },
  StatCard: {
    description: 'Metric display card with change indicator and sparkline slot',
    category: 'composition' as const,
    schema: 'StatCardPropsSchema',
    variants: [],
    engines: true,
    usage: '<StatCard title="Revenue" value="$12.4k" change={5.2} engine="grow" />',
  },
  DataTable: {
    description: 'Sortable data table with Surface container',
    category: 'composition' as const,
    schema: 'DataTablePropsSchema',
    variants: [],
    engines: true,
    usage: '<DataTable columns={cols} rows={data} engine="govern" />',
  },
  NavigationLink: {
    description: 'Navigation link with icon and engine hover state',
    category: 'composition' as const,
    schema: 'NavigationLinkPropsSchema',
    variants: [],
    engines: true,
    usage: '<NavigationLink href="/protect" engine="protect" icon={<ShieldIcon />}>Protect</NavigationLink>',
  },
  Modal: {
    description: 'Radix Dialog wrapper with DS surface tokens',
    category: 'composition' as const,
    schema: 'ModalPropsSchema',
    variants: [],
    engines: false,
    usage: '<Modal open={open} onOpenChange={setOpen} title="Confirm">...</Modal>',
  },
  BottomSheet: {
    description: 'Mobile bottom sheet with grab handle',
    category: 'composition' as const,
    schema: 'BottomSheetPropsSchema',
    variants: [],
    engines: false,
    usage: '<BottomSheet open={open} onOpenChange={setOpen} title="Options">...</BottomSheet>',
  },
  DSToast: {
    description: 'Notification toast with variant-based styling',
    category: 'composition' as const,
    schema: 'DSToastPropsSchema',
    variants: ['info', 'success', 'warning', 'error'],
    engines: false,
    usage: '<DSToast variant="success" title="Saved" onClose={dismiss} />',
  },
  CommandPaletteItem: {
    description: 'Command palette row with keyboard shortcut',
    category: 'composition' as const,
    schema: 'CommandPaletteItemPropsSchema',
    variants: [],
    engines: true,
    usage: '<CommandPaletteItem label="Search" shortcut="⌘K" engine="govern" />',
  },

  // ── AI ──────────────────────────────────────────────────────
  AIInsightBanner: {
    description: 'GenAI explanation banner with confidence display',
    category: 'ai' as const,
    schema: 'AIInsightBannerPropsSchema',
    variants: [],
    engines: true,
    usage: '<AIInsightBanner title="AI Insight" engine="grow" confidence={0.92}>...</AIInsightBanner>',
  },
  AIThinking: {
    description: 'Animated thinking indicator for AI operations',
    category: 'ai' as const,
    schema: 'AIThinkingPropsSchema',
    variants: [],
    engines: true,
    usage: '<AIThinking label="Analyzing..." engine="grow" />',
  },
  ConfidenceRing: {
    description: 'Circular confidence meter with auto-coloring',
    category: 'ai' as const,
    schema: 'ConfidenceRingPropsSchema',
    variants: [],
    engines: true,
    usage: '<ConfidenceRing value={0.87} size={64} engine="grow" />',
  },
  FactorBar: {
    description: 'SHAP-style feature attribution bar',
    category: 'ai' as const,
    schema: 'FactorBarPropsSchema',
    variants: [],
    engines: false,
    usage: '<FactorBar label="Income" value={0.45} />',
  },
  TypewriterText: {
    description: 'Animated text reveal with cursor',
    category: 'ai' as const,
    schema: 'TypewriterTextPropsSchema',
    variants: [],
    engines: false,
    usage: '<TypewriterText text="AI response here..." speed={30} />',
  },

  // ── Data-viz ────────────────────────────────────────────────
  SparkLine: {
    description: 'Inline SVG trend line chart',
    category: 'data-viz' as const,
    schema: 'SparkLinePropsSchema',
    variants: [],
    engines: true,
    usage: '<SparkLine data={[10,20,15,30]} engine="grow" />',
  },
  DSAreaChart: {
    description: 'Recharts area chart wrapper with DS styling',
    category: 'data-viz' as const,
    schema: 'DSAreaChartPropsSchema',
    variants: [],
    engines: true,
    usage: '<DSAreaChart data={data} dataKey="value" engine="grow" />',
  },
  DSBarChart: {
    description: 'Recharts bar chart wrapper with DS styling',
    category: 'data-viz' as const,
    schema: 'DSBarChartPropsSchema',
    variants: ['vertical', 'horizontal'],
    engines: true,
    usage: '<DSBarChart data={data} dataKey="value" engine="execute" />',
  },
  RingProgress: {
    description: 'Large circular progress with label',
    category: 'data-viz' as const,
    schema: 'RingProgressPropsSchema',
    variants: [],
    engines: true,
    usage: '<RingProgress value={75} label="Score" engine="protect" />',
  },
  HeatMap: {
    description: 'Grid heat map with intensity coloring',
    category: 'data-viz' as const,
    schema: 'HeatMapPropsSchema',
    variants: [],
    engines: true,
    usage: '<HeatMap data={grid} columns={7} engine="execute" />',
  },

  // ── Effects ─────────────────────────────────────────────────
  GlassPanel: {
    description: 'Glass-morphism container with configurable blur',
    category: 'effects' as const,
    schema: 'GlassPanelPropsSchema',
    variants: [],
    engines: false,
    usage: '<GlassPanel blur={12} opacity={0.1}>...</GlassPanel>',
  },
  GlowBorder: {
    description: 'Animated gradient border with engine glow',
    category: 'effects' as const,
    schema: 'GlowBorderPropsSchema',
    variants: [],
    engines: true,
    usage: '<GlowBorder engine="protect" intensity="medium">...</GlowBorder>',
  },
  NeuralBackground: {
    description: 'SVG particle network background',
    category: 'effects' as const,
    schema: 'NeuralBackgroundPropsSchema',
    variants: [],
    engines: true,
    usage: '<NeuralBackground engine="grow" nodeCount={30} />',
  },
  PulsingOrb: {
    description: 'Breathing glow orb for ambient effects',
    category: 'effects' as const,
    schema: 'PulsingOrbPropsSchema',
    variants: [],
    engines: true,
    usage: '<PulsingOrb engine="protect" size={200} />',
  },
  AuroraGradient: {
    description: 'Northern lights gradient overlay',
    category: 'effects' as const,
    schema: 'AuroraGradientPropsSchema',
    variants: [],
    engines: true,
    usage: '<AuroraGradient engine="grow" intensity="subtle" />',
  },
  GridOverlay: {
    description: 'CSS grid lines overlay',
    category: 'effects' as const,
    schema: 'GridOverlayPropsSchema',
    variants: [],
    engines: true,
    usage: '<GridOverlay engine="govern" cellSize={40} />',
  },
} as const

export type ComponentName = keyof typeof componentCatalog
export type ComponentCategory = 'primitive' | 'composition' | 'ai' | 'data-viz' | 'effects'
